### ISSUE TITLE
[BUG] Cannot use GetBooleanDetails with .NET SDK

### ISSUE THREAD

**Issue by tomflenner** [open-feature/flagd#1302]
### Observed behavior

With a simple boolean flag generated from [Playground](https://flagd.dev/playground/) :

```
{
  "$schema": "https://flagd.dev/schema/v0/flags.json",
  "flags": {
    "basic-boolean": {
      "state": "ENABLED",
      "defaultVariant": "false",
      "variants": {
        "true": true,
        "false": false
      },
      "targeting": {}
    }
  }
}
```

When I use .NET SDK FeatureClient following call : 
`FlagEvaluationDetails<bool>? flag = await featureClient.GetBooleanDetails(flagKey, false);`

I have this error :
```
{
    "errorMessage": "Method not found: 'Void OpenFeature.Model.ResolutionDetails`1..ctor(System.String, !0, OpenFeature.Constant.ErrorType, System.String, System.String, System.String)'.",
    "errorType": 5,
    "flagKey": "basic-boolean",
    "flagMetadata": null,
    "reason": "ERROR",
    "value": false,
    "variant": ""
}
```

### Expected Behavior

The response should not contain any error and return me the current value of the feature flag with :
`reason: "STATIC"`

Like the playground

### Steps to reproduce

1 sync http (Node.js Express with Typescript) :
```
import express, { Request, Response } from "express";

const app = express();

const flagsJson = {
  $schema: "https://flagd.dev/schema/v0/flags.json",
  flags: {
    "basic-boolean": {
      state: "ENABLED",
      defaultVariant: "false",
      variants: {
        true: true,
        false: false,
      },
      targeting: {},
    },
  },
};

app.get("/flagd", (req: Request, res: Response) => {
  res.json(flagsJson);
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
```

1 .NET 8 minimal api :
```
using Microsoft.AspNetCore.Mvc;
using OpenFeature;
using OpenFeature.Contrib.Providers.Flagd;
using OpenFeature.Model;

await Api.Instance.SetProviderAsync(new FlagdProvider());

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHealthChecks();
builder.Services.AddMvc();
var app = builder.Build();

app.MapHealthChecks("/healthz");
app.MapGet("/featureFlag",
    async ([FromQuery(Name = "flagKey")] string flagKey) =>
{
    IFeatureClient featureClient = Api.Instance.GetClient();
    FlagEvaluationDetails<bool>? flag = await featureClient.GetBooleanDetails(flagKey, false);
    return Results.Ok(flag);
});

app.MapGet("/flagd", async() => {
    HttpClient client = new HttpClient();
    var response = await client.GetAsync("http://http-sync:3000/flagd");
    if (!response.IsSuccessStatusCode)
    {
        return Results.StatusCode((int)response.StatusCode);
    }
    string json = await response.Content.ReadAsStringAsync();
    return Results.Ok(json);
});

await app.RunAsync();
```

A docker-compose like that :
```
version: '3'

services:
  http-sync:
    build:
      context: ./HttpSync
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  flagd:
    image: ghcr.io/open-feature/flagd:latest
    command: "start --debug --uri http://http-sync:3000/flagd"
    ports:
      - "8013:8013"
      - "8016:8016"
    depends_on:
      - http-sync

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
```

 HTTP GET backend:8080/featureFlag?flagKey="basic-boolean"
