### ISSUE TITLE
chore: investigate performance optimization in JSONEvaluator

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#685]
Specifically, it may be that we're marshaling json multiple times unnecessarily with each evaluation, when we could be caching the `targeting` until it's changed: https://github.com/open-feature/flagd/blob/13bb13daa11068481ba97f3432ae08de78392a91/core/pkg/eval/json_evaluator.go#L299

There may be other examples as well.

It would be great if we could confirm whether the above is an issue or not, and also look for other low-hanging optimizations.

**Comment by bacherfl** [comment]
having done some work with the json evaluator recently, I'd like to look into this one

**Comment by bacherfl** [comment]
After investigating this, I believe the calls to `MarshalJSON` are not a problem in this case, as the targeting rules are stored as `json.RawMessage`, which is essentially a type alias for `[]byte`. This means that the `MarshalJSON()` method just returns the targetingRule's value directly, without any computation being done within this method.

I did take the opportunity to do some load testing of flagd though, and would like to summarize my results here.
For the setup, I created a `FeatureFlagConfig` K8s CR containing 5000 flags, each containing the following targetingRule:

```json
{
"if": [
  {
     "sem_ver": [{"var": "version"}, ">", "0.1.0"]
  },
  "red", "green"
]
}
```

Flagd was deployed using the following manifest (leaving out some overhead of the manifest to improve readability):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd
  namespace: flagd-performance-test
  labels:
    app: flagd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app: flagd
    spec:
      containers:
        - name: flagd
          image: bacherfl/flagd:latest
          args:
            - start
            - '--uri'
            - >-
              core.openfeature.dev/flagd-performance-test/benchmark-flag-source-config
            - '-x'
          resources:
            limits:
              cpu: 500m
              memory: 64M
            requests:
              cpu: 200m
              memory: 32M
```

The load test was executed using `k6` and `testkube`, using the following script:

```javascript
import http from 'k6/http';
import { check } from 'k6';
import { sleep } from 'k6';

export const options = {
    stages: [
        { target: 10, duration: '3m' },
        { target: 50, duration: '3m' },
        { target: 100, duration: '3m' },
        { target: 200, duration: '3m' },
        { target: 300, duration: '3m' },
        { target: 500, duration: '3m' },
        { target: 1000, duration: '3m' },
        { target: 2000, duration: '3m' },
        { target: 3000, duration: '3m' },
        { target: 5000, duration: '3m' },
        { target: 10000, duration: '3m' },
    ],
};
export default function () {
    const url = 'http://flagd.flagd-performance-test:80/schema.v1.Service/ResolveString';

    var randomNumber = Math.floor(Math.random() * 5000);

    const payload = {
        flagKey: 'color-' + randomNumber,
        context: {
            "version": "1.0.0"
        }
    };
    const headers = {
        'Content-Type': 'application/json'
    };

    const response = http.post(url, JSON.stringify(payload), { headers });

    check(response, {
        'http response status code is 200': response.status === 200,
    });

    sleep(10)
}
```

Essentially, this script ramps up the number of virtual users accessing the flagd API from 0 to 5000 users, where each sends a request for one of the 5k flags of the FeatureFlagConfiguration and waits for 10ms before sending the next request.
Executing this test resulted in the following graph in Dynatrace:

![Flagd-performance](https://github.com/open-feature/flagd/assets/2143586/52d922b6-ac70-44a1-9f02-0a9b68d9445b)

Looking at the graph, the response time stayed at a p99 value of ~20ms up to a throughput of ~13.7k requests per minute and increased significantly after exceeding that request rate, with failing requests occurring after some time at a sustained high request rate.

So right now, looking at the JSON Evaluator I do not think there is much to be improved, but it may be valuable to keep the test setup I have created for this issue somewhere for future performance tests. @toddbaert where do you think would be the best place to store the test setup to make this reproducible as easily as possible?
