### ISSUE TITLE
[FEATURE] Only build flagd.dev on push to /web-docs

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#810]
### Requirements

https://flagd.dev action should only be built when files are changed inside `/web-docs`. Anything outside this folder is not represented on the website and thus is out of scope.

Looking at the [current build workflow](https://github.com/open-feature/flagd/blob/main/.github/workflows/build.yaml#L3-#L16) it seems that it works on a deny list model with `paths-ignore`. Instead, we could move to an allow list model with `paths`:

```
on:
  push:
    branches:
      - feature/workflows
      - main
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docs/**"
```

This can be done like this meaning explicitely only build if something in `web-docs` has changed.

```
on:
  push:
    branches:
      - main
    paths:
      - web-docs/**
```
